const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),safeUrl=v=>{if(typeof v!=='string'||v.startsWith('//')||!/^https?:\/\//.test(v))return'';try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)&&u.host?u.href:''}catch{return''}},label=(v,group)=>({review:{reviewed:'已审核',draft:'待审核',rejected:'未通过'},document:{txt:'文本资料',md:'Markdown资料',html:'网页资料',htm:'网页资料'},license:{official_public_reference:'官方公开引用',licensed:'已获许可',internal_review:'内部审核',unknown:'许可待确认',restricted:'受限'},claim:{reported_fact:'资料报告命题',measured_fact:'实测命题',inference:'推断命题',hypothesis:'假设命题'},evidence:{direct_quote:'原文直接引文',table_value:'表格数据',calculation:'计算结果',expert_review:'专家复核',official_revision_note:'官方修订说明'},basis:{reported:'资料报告值',measured:'实测值',calculated:'计算值',estimated:'估算值',forecast:'预测值',target:'目标值',theoretical:'理论值'}}[group]?.[v]||v);
fetch('data/knowledge-records.json').then(async r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}).then(d=>{
 $('#toolNotice').textContent=d.meta.notice;
 $('#capabilityGrid').innerHTML=d.capabilities.map(x=>`<article class="system-card"><span class="code">${esc(x.capability_id)} · ${x.status==='implemented'?'已实现':'待建设'}</span><h3>${esc(x.name_zh)}</h3><p>${esc(x.boundary)}</p></article>`).join('');
 $('#documentGrid').innerHTML=d.documents.map(x=>{const url=safeUrl(x.official_url);return `<article class="system-card"><span class="code">${esc(x.document_id)} · ${esc(label(x.review_status,'review'))}</span><h3>${esc(x.title)}</h3><p>${esc(x.source_id)} · ${esc(label(x.document_type,'document'))} · ${esc(label(x.license_status,'license'))}</p>${url?`<a href="${esc(url)}" target="_blank" rel="noopener">访问官方资料（新窗口）</a>`:''}</article>`}).join('')||'<div class="empty"><h3>没有可公开显示的资料</h3><p>资料需同时满足公开访问和审核通过条件。</p></div>';
 const evidenceById=new Map(d.evidence.map(x=>[x.evidence_id,x])),citationById=new Map(d.citations.map(x=>[x.citation_id,x])),documentById=new Map(d.documents.map(x=>[x.document_id,x]));
 $('#claimGrid').innerHTML=d.claims.map((claim,index)=>{const links=d.claim_evidence.filter(x=>x.claim_id===claim.claim_id);const evidence=links.map(x=>evidenceById.get(x.evidence_id)).filter(Boolean);return `<section class="policy-level-section"><div class="policy-level-heading"><span class="count">${index+1}</span><div><p class="eyebrow">${esc(label(claim.claim_type,'claim'))} · ${esc(label(claim.review_status,'review'))}</p><h2>${esc(claim.statement)}</h2></div></div>${evidence.map(item=>{const citation=citationById.get(item.citation_id),document=documentById.get(citation?.document_id);return `<article class="detail-card"><span class="code">证据等级 ${esc(item.evidence_level)} · ${esc(label(item.evidence_type,'evidence'))}</span><blockquote>${esc(citation?.quote||'')}</blockquote><p>定位：${esc(citation?.locator||'未提供')} · 来源：${esc(document?.title||'未公开资料')}</p></article>`}).join('')}</section>`}).join('')||'<div class="empty"><h3>没有审核通过的知识命题</h3><p>命题必须具有公开、审核通过且明确支持的证据。</p></div>';
 $('#metricGrid').innerHTML=d.metrics.map(x=>`<article class="system-card"><span class="code">${esc(x.metric_id)} · ${esc(label(x.measurement_basis,'basis'))}</span><h3>${esc(x.metric_name)}</h3><p>对象：${esc(x.object_id)}</p><p><b>${esc(x.value)} ${esc(x.unit)}</b> · 观测日期：${esc(x.observed_at||'未注明')}</p><p>引文：${esc(x.citation_id)}</p></article>`).join('')||'<div class="empty"><h3>没有审核通过的量化指标</h3><p>指标需关联已审核对象、计量基础和公开引文。</p></div>';
 $('#factGrid').innerHTML=d.facts.map(x=>`<article class="system-card"><span class="code">${esc(x.fact_id)} · ${esc(label(x.measurement_basis,'basis'))}</span><h3>${esc(x.predicate)}</h3><p>对象：${esc(x.object_id)} · 值：${esc(x.value)} · 生效日期：${esc(x.valid_from||'未注明')}</p></article>`).join('')||'<div class="empty"><h3>没有审核通过的结构化事实</h3><p>结构化事实需关联已审核对象和公开引文。</p></div>';
}).catch(e=>{$('#claimGrid').innerHTML=`<div class="empty"><h3>${esc(e.message)}</h3></div>`;console.error(e)});
